name: CI Web

on:
  pull_request:
    paths:
      - 'apps/web/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/**'

jobs:
  web:
    name: ci/web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm --filter @estimatex/web build

